routes/web.php
<?php

use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\EmployeeController;
use App\Http\Controllers\Admin\MainController;
use Illuminate\Support\Facades\Route;



Route::get('/', [MainController::class, 'dashboard'])->name('dashboard');
Route::resource('/departments', DepartmentController::class);
Route::resource('/employees', EmployeeController::class);

app/Models/Admin/Department.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;

    protected $fillable = ['title'];

    public function employees()
    {
        return $this->belongsToMany(Employee::class);
    }
}

app/Models/Admin/Employee.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function getGenderAttribute($attribute)
    {
        return [
            0 => 'Мужской',
            1 => 'Женский',
        ][$attribute];
    }

    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->middle_name} {$this->last_name}";
    }

    public function departments()
    {
        return $this->belongsToMany(Department::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/DepartmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Admin\Department;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        return view('admin.department.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required',
        ]);

        Department::create($validatedData);
        return redirect()->route('departments.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Department $department
     * @return Application|Factory|View
     */
    public function edit(Department $department)
    {
        return view('admin.department.edit', compact('department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Department $department
     * @return RedirectResponse
     */
    public function update(Request $request, Department $department)
    {
        $validatedData = $request->validate([
            'title' => 'required',
        ]);
        $department->update($validatedData);
        return redirect()->route('departments.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Department $department
     * @return RedirectResponse
     */
    public function destroy(Department $department)
    {
        if($department->employees->count() > 0) {
            return back();
        }
        $department->delete();
        return back();
    }
}

app/Http/Controllers/Admin/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\EmployeeRequest;
use App\Models\Admin\Department;
use App\Models\Admin\Employee;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $employees = Employee::all();
        return view('admin.employee.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.employee.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param EmployeeRequest $request
     * @return RedirectResponse
     */
    public function store(EmployeeRequest $request)
    {
        $employee = Employee::create([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'middle_name' => $request->middle_name,
            'gender' => $request->gender,
            'salary' => $request->salary,
        ]);

        $employee->departments()->attach($request->departments);

        return redirect()->route('employees.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Employee $employee
     * @return Application|Factory|View
     */
    public function edit(Employee $employee)
    {
        return view('admin.employee.edit', compact('employee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param EmployeeRequest $request
     * @param Employee $employee
     * @return RedirectResponse
     */
    public function update(EmployeeRequest $request, Employee $employee)
    {
        $employee->update($request->except('departments'));
        $employee->departments()->sync($request->departments);
        return redirect()->route('employees.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Employee $employee
     * @return RedirectResponse
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        return back();
    }
}

app/Http/Controllers/Admin/MainController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class MainController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function dashboard()
    {

        return view('admin.pages.dashboard');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{

}

resources/views/admin/department/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Отделы')

@section('breadcrumb-item')
    <li class="breadcrumb-item active"><a href="{{ route('departments.index') }}">Отделы</a></li>
    <li class="breadcrumb-item active">Создать отдел</li>
@endsection

@section('mainContent')
    <section class="content mt-5">
        <div class="card card-primary">
            <form role="form" action="{{ route('departments.store') }}" method="POST">
                @csrf
                <div class="form-group mx-3">
                    <label for="title">Название Отдела</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="Введите Название Отдела" value="{{ old('title') }}" autofocus>
                    @error('title') <span class="text-danger error">{{ $message }}</span>@enderror
                </div>
                <div class="card-footer text-center">
                    <button type="submit" class="btn btn-primary">Создать</button>
                    <a href="{{ route('departments.index') }}" class="btn btn-warning">Назад</a>
                </div>
            </form>
        </div>
    </section>
@endsection

resources/views/admin/department/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Отделы')

@section('breadcrumb-item')
    <li class="breadcrumb-item active"><a href="{{ route('departments.index') }}">Отделы</a></li>
    <li class="breadcrumb-item active">Редактировать отдел</li>
@endsection

@section('mainContent')
    <section class="content mt-5">
        <div class="card card-primary">
            <form role="form" action="{{ route('departments.update', $department) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group mx-3">
                    <label for="title">Название Отдела</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="Введите Название Отдела" value="{{ $department->title }}" autofocus>
                    @error('title') <span class="text-danger error">{{ $message }}</span>@enderror
                </div>
                <div class="card-footer text-center">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                    <a href="{{ route('departments.index') }}" class="btn btn-warning">Назад</a>
                </div>
            </form>
        </div>
    </section>
@endsection

resources/views/admin/department/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Отделы')

@section('breadcrumb-item')
    <li class="breadcrumb-item active">Отделы</li>
@endsection

@section('mainContent')
    <div class="card mb-4">
        @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        <div class="card-header text-center">
            <a href="{{ route('departments.create') }}" class="btn btn-success">
                Создать Отдел
                <i class="fas fa-plus mr-1"></i>
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered mt-5">
                    <thead>
                    <tr>
                        <th>Наименование отдела</th>
                        <th>Количество сотрудников отдела</th>
                        <th>Максимальная заработная плата</th>
                        <th>Действия</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($departments as $value)
                        <tr>
                            <td>{{ $value->title }}</td>
                            <td>{{ $value->employees->count() > 0 ? $value->employees->count() : ""}}</td>
                            <td>{{ $value->employees->pluck('salary')->max() }}</td>
                            <td>
                                <div class="row pl-3">
                                    <a class="btn btn-success btn-sm ml-2"
                                       href="{{ route('departments.edit', $value) }}"><i
                                            class="fas fa-pen-square"></i></a></p>

                                    <form action="{{ route('departments.destroy', $value) }}" method="POST"
                                          id="deleteForm-{{ $value->id }}" style="display: none">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                    <a class="btn btn-danger btn-sm ml-2" href="" onclick="
                                        if(confirm('Вы действительно желаете удалить этот отдел?')){
                                        event.preventDefault();
                                        document.getElementById('deleteForm-{{ $value->id }}').submit();
                                        }else{
                                        event.preventDefault();
                                        }"><i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/employee/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Сотрудники')

@section('breadcrumb-item')
    <li class="breadcrumb-item active"><a href="{{ route('employees.index') }}">Сотрудники</a></li>
    <li class="breadcrumb-item active">Добавить сотрудника</li>
@endsection

@section('mainContent')
    <section class="content mt-5">
        <div class="card card-primary">
            <form role="form" action="{{ route('employees.store') }}" method="POST">
                @csrf
                <div class="row">
                    <div class="form-group col-md-4" data-select2-id="38">
                        <label for="first_name">Имя сотрудника</label>
                        <input type="text" class="form-control" id="first_name" name="first_name"
                               placeholder="Введите имя сотрудника" value="{{ old('first_name') }}" autofocus>
                        @error('first_name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="form-group col-md-4">
                        <label for="middle_name">Отчество сотрудника</label>
                        <input type="text" class="form-control" id="middle_name" name="middle_name"
                               placeholder="Введите отчество сотрудника" value="{{ old('middle_name') }}">
                        @error('middle_name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="form-group col-md-4">
                        <label for="last_name">Фамилия сотрудника</label>
                        <input type="text" class="form-control" id="last_name" name="last_name"
                               placeholder="Введите фамилию сотрудника" value="{{ old('last_name') }}">
                        @error('last_name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="gender">Пол</label>
                        <select class="form-control" name="gender" id="gender">
                            <option value="" selected disabled>Выберите пол</option>
                            <option value="0">Мужской</option>
                            <option value="1">Женский</option>
                        </select>
                        @error('gender') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="form-group col-md-4">
                        <label for="salary">Заработная плата</label>
                        <input type="text" class="form-control" id="salary" name="salary"
                               placeholder="Введите заработную плату сотрудника" value="{{ old('salary') }}">
                        @error('salary') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="form-check col-md-4">
                        <label>Отделы</label><br>
                        @foreach($departments as $department)
                            <input class="form-check-input mx-1" type="checkbox" value="{{ $department->id }}" name="departments[]" id="departments">
                            <label class="form-check-label mx-4" for="departments">{{ $department->title }}</label>
                        @endforeach
                        <br>
                        @error('departments') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                </div>
                <div class="card-footer text-center">
                    <button type="submit" class="btn btn-primary">Создать</button>
                    <a href="{{ route('employees.index') }}" class="btn btn-warning">Назад</a>
                </div>
            </form>
        </div>
    </section>
@endsection

resources/views/admin/employee/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Сотрудники')

@section('breadcrumb-item')
    <li class="breadcrumb-item active"><a href="{{ route('employees.index') }}">Сотрудники</a></li>
    <li class="breadcrumb-item active">Редактировать данные сотрудника</li>
@endsection

@section('mainContent')
    <section class="content mt-5">
        <div class="card card-primary">
            <form role="form" action="{{ route('employees.update', $employee) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="first_name">Имя сотрудника</label>
                        <input type="text" class="form-control" id="first_name" name="first_name"
                               placeholder="Введите имя сотрудника" value="{{ $employee->first_name }}" autofocus>
                        @error('first_name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="form-group col-md-4">
                        <label for="middle_name">Отчество сотрудника</label>
                        <input type="text" class="form-control" id="middle_name" name="middle_name"
                               placeholder="Введите отчество сотрудника" value="{{ $employee->middle_name }}">
                        @error('middle_name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="form-group col-md-4">
                        <label for="last_name">Фамилия сотрудника</label>
                        <input type="text" class="form-control" id="last_name" name="last_name"
                               placeholder="Введите фамилию сотрудника" value="{{ $employee->last_name }}">
                        @error('last_name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="gender">Пол</label>
                        <select class="form-control" name="gender" id="gender">
{{--                            <option value="" selected disabled>Выберите пол</option>--}}
{{--                            @dd($employee->gender)--}}
                            <option value="0" @if($employee->gender == 'Мужской') selected @endif>Мужской</option>
                            <option value="1" @if($employee->gender == 'Женский') selected @endif>Женский</option>
                        </select>
                        @error('gender') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="form-group col-md-4">
                        <label for="salary">Заработная плата</label>
                        <input type="text" class="form-control" id="salary" name="salary"
                               placeholder="Введите заработную плату сотрудника" value="{{ $employee->salary }}">
                        @error('salary') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <div class="form-group col-md-4">
                        <label>Отделы</label><br>
                        @foreach($departments as $department)
                            <input class="form-check-input mx-1" type="checkbox" value="{{ $department->id }}"
                                   name="departments[]" id="departments" @if($employee->departments->pluck('id')->contains($department->id)) checked @endif>
                            <label class="form-check-label mx-4" for="departments">{{ $department->title }}</label>
                        @endforeach
                        <br>
                        @error('departments') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                </div>
                <div class="card-footer text-center">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                    <a href="{{ route('employees.index') }}" class="btn btn-warning">Назад</a>
                </div>
            </form>
        </div>
    </section>
@endsection

resources/views/admin/employee/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Отделы')

@section('breadcrumb-item')
    <li class="breadcrumb-item active">Сотрудники</li>
@endsection

@section('mainContent')
    <div class="card mb-4">
        @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        <div class="card-header text-center">
            <a href="{{ route('employees.create') }}" class="btn btn-success">
                Добавить сотрудника
                <i class="fas fa-plus mr-1"></i>
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered mt-5">
                    <thead>
                    <tr>
                        <th>Имя сотрудника</th>
                        <th>Пол</th>
                        <th>Заработная плата</th>
                        <th>Отделы</th>
                        <th>Действия</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($employees as $value)
                        <tr>
                            <td>{{ $value->full_name }}</td>
                            <td>{{ $value->gender }}</td>
                            <td>{{ $value->salary }}</td>
{{--                            @dd($value)--}}
                            <td>
                                @foreach($value->departments as $item)
                                    {{ $item->title }} {{ $loop->last ? "" : ',' }}
                                @endforeach
                            </td>
                            <td>
                                <div class="row pl-3">
                                    <a class="btn btn-success btn-sm ml-2"
                                       href="{{ route('employees.edit', $value) }}"><i
                                            class="fas fa-pen-square"></i></a></p>

                                    <form action="{{ route('employees.destroy', $value) }}" method="POST"
                                          id="deleteForm-{{ $value->id }}" style="display: none">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                    <a class="btn btn-danger btn-sm ml-2" href="" onclick="
                                        if(confirm('Вы действительно желаете удалить этого сотрудника?')){
                                        event.preventDefault();
                                        document.getElementById('deleteForm-{{ $value->id }}').submit();
                                        }else{
                                        event.preventDefault();
                                        }"><i class="fas fa-trash-alt"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/includes/breadcrumb.blade.php
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item">
            <a href="{{ route('dashboard') }}">Главная</a>
    </li>
    @yield('breadcrumb-item')
</ol>

resources/views/admin/includes/footer.blade.php
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Made by Giorgi 2021</div>
        </div>
    </div>
</footer>

resources/views/admin/includes/leftSidebar.blade.php
<nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <a class="nav-link {{ Request::is('/') ? 'active' : '' }}" href="{{ route('dashboard') }}">
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Главная
            </a>
            <a class="nav-link {{ Request::is('/departments') ? 'active' : '' }}" href="{{ route('departments.index') }}">
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Отделы
            </a>
            <a class="nav-link {{ Request::is('/employees') ? 'active' : '' }}" href="{{ route('employees.index') }}">
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Сотрудники
            </a>
        </div>
    </div>
</nav>

resources/views/admin/includes/topNavbar.blade.php
<nav class="sb-topnav navbar navbar-expand navbar-light bg-light">
    <a class="navbar-brand" href="{{ route('dashboard') }}"><img src="{{ asset('img/gicon.png') }}" alt="" width="40"></a>
    <!-- Boorger button-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 " id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- cstom content-->
    <div class="d-none d-md-inline-block ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <!-- content-->
        </div>
    </div>
    <ul class="navbar-nav ml-auto ml-md-0">
        <!-- content-->
    </ul>
</nav>

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link rel="shortcut icon" type="image/x-icon" href="{{ asset('img/icon.ico') }}">
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>
    <link href="{{ asset('admin-panel/css/main.css') }}" rel="stylesheet"/>
    <link href="{{ asset('admin-panel/css/app.css') }}" rel="stylesheet"/>

    <title>@yield('links')</title>
</head>
<body class="sb-nav-fixed">
@include('admin.includes.topNavbar')
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        @include('admin.includes.leftSidebar')
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                @include('admin.includes.breadcrumb')
                @yield('mainContent')
            </div>
        </main>
       @include('admin.includes.footer')
    </div>
</div>
<script src="{{ asset('admin-panel/js/app.js') }}"></script>

@yield('script')
</body>
</html>

resources/views/admin/pages/dashboard.blade.php
@extends('admin.layouts.app')
@section('title', 'Админ-панель')


@section('mainContent')
    <div class="card mb-4">
        @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        <div class="card-header">
            <h2>Сводная таблица</h2>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered mt-5">
                    <thead>
                    <tr>
                        <th></th>
                        @foreach($departments as $department)
                            <th>{{ $department->title }}</th>
                        @endforeach
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($employees as $value)
                        <tr>
                            <td>{{ $value->full_name}}</td>
                            <td>
{{--                                @dd($value->departments->pluck('id'))--}}
                                @if($value->departments->pluck('id')->contains('1'))
                                    <span class="text-success text-center"><i class="fas fa-check"></i></span>
                                @endif
                            </td>
                            <td>
                               @if($value->departments->pluck('id')->contains('2'))
                                    <span class="text-success text-center"><i class="fas fa-check"></i></span>
                                @endif
                            </td>
                            <td>
                               @if($value->departments->pluck('id')->contains('3'))
                                    <span class="text-success text-center"><i class="fas fa-check"></i></span>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection